# Generated by Django 2.0.2 on 2018-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='none', max_length=5)),
                ('recorded', models.CharField(default='none', max_length=15)),
                ('date', models.CharField(default='none', max_length=10)),
                ('grantor', models.CharField(default='none', max_length=50)),
                ('address', models.CharField(default='none', max_length=50)),
                ('city', models.CharField(default='none', max_length=30)),
                ('grantee', models.CharField(default='none', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('propType', models.CharField(default='none', max_length=3)),
                ('built', models.CharField(default='none', max_length=5)),
                ('acreage', models.FloatField(default=0.0)),
                ('impsq', models.FloatField(default=0.0)),
                ('units', models.FloatField(default=0.0)),
                ('landsq', models.FloatField(default=0.0)),
                ('sfimp', models.CharField(default='none', max_length=10)),
                ('unitimp', models.CharField(default='none', max_length=10)),
                ('sfland', models.CharField(default='none', max_length=10)),
                ('garage', models.FloatField(default=0.0)),
                ('caprate', models.FloatField(default=0.0)),
                ('noi', models.FloatField(default=0.0)),
                ('exp', models.FloatField(default=0.0)),
                ('egi', models.FloatField(default=0.0)),
                ('occup', models.FloatField(default=0.0)),
                ('corner', models.CharField(default='none', max_length=5)),
                ('regshape', models.CharField(default='none', max_length=10)),
                ('utilities', models.CharField(default='none', max_length=20)),
                ('location', models.FloatField(default=0.0)),
                ('quality', models.FloatField(default=0.0)),
                ('condition', models.FloatField(default=0)),
                ('description', models.CharField(default='none', max_length=50)),
                ('comments', models.CharField(default='none', max_length=50)),
            ],
        ),
    ]
