# Generated by Django 2.0.2 on 2018-04-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180410_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='acreage',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
