# Generated by Django 2.0.2 on 2018-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180410_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='caprate',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='egi',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='exp',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='impsq',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='landsq',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='noi',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='occup',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='quality',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='units',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
